language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "9"

cache: yarn

script:
  - yarn test

jobs:
  include:
    - stage: npm release
      node_js: "9"
      script: echo "Deploying to npmâ€¦"
      deploy:
        provider: npm
        email: npmjs@squareup.com
        api_key: $NPM_TOKEN
        on:
          repo: square/find-yarn-workspace-root
          branch: master
